### ISSUE TITLE
TypeScript

### ISSUE THREAD

**Issue by mightyiam** [tjoskar/simple-spy#18]
@tjoskar would you mind if I convert all the code to TypeScript?

**Comment by mightyiam** [comment]
No breaking changes, I promise.

**Comment by tjoskar** [comment]
Is there any reason for a rewrite? It exists a [index.d.ts](https://github.com/tjoskar/simple-spy/blob/master/index.d.ts) file today so it works fine with typescripts projects.
I'm a big fan of typescript but it will add some complexity; build step, AVA does not support typescript so we need to manually build the ts files first, we need to pass the source maps to [nyc](https://github.com/istanbuljs/nyc) and more.

The code is very simple today and I'm not sure it will bring any value to convert it to typescript. Or am I wrong?

**Comment by tjoskar** [comment]
I'm not against, I'm just skeptical :)

**Comment by mightyiam** [comment]
I have experience with small TypeScript projects and converting small JS projects to TypeScript. I love it.

What I do is `npx tsc --watch` in one terminal and `npx ava --watch --fail-fast` in another. Works flawlessly, for me in numerous projects.

AVA does have TypeScript types and I know how to use them 😄 .

One possible advantage is better typing because they are autogenerated. At least not wrong typings.

**Comment by tjoskar** [comment]
Okay, I will accept a PR :)

**Comment by tjoskar** [comment]
Thanks @mightyiam 🎉
