### ISSUE TITLE
Accept undefined as function

### ISSUE THREAD

**Issue by tjoskar** [tjoskar/simple-spy#19]
From time to time I just want to create a mock and do not care about the return value of a function, often for functions that create side effects.

To mock these functions I currently have to do something like:
```js
const myMock = spy(() => null);
```

I want to be able to just call `spy` without arguments:
```js
const myMock = spy();
```

Implementation suggestion:
```diff
-function spy(fn) {
+function spy(fn = () => undefined) {
```

**Comment by mightyiam** [comment]
I'll do it.

**Comment by mightyiam** [comment]
After #18.

**Comment by Gyran** [comment]
Sorry for "stealing" this. Was looking for something useful to do for https://hacktoberfest.digitalocean.com
