### ISSUE TITLE
Doesn't retain arity

### ISSUE THREAD

**Issue by mightyiam** [tjoskar/simple-spy#2]
I'd like to refrain from switching to sinon or something.

Here's an example:
https://github.com/sinonjs/sinon/pull/681/files

**Comment by tjoskar** [comment]
Interesting. I guess you want something like this to pass:

```javascript
test('the stub-function length should match the real-function length', t => {
    const fun = (a, b, c) => a + b + c;
    const funSpy = spy(fun);

    t.is(funSpy.length, 3);
});
```

**Comment by tjoskar** [comment]
I'm up for it. PR are always welcome, otherwise I will take a look at it next week :)
